# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

ARG PYTHON_VERSION=3.9.13
FROM python:${PYTHON_VERSION}-slim-bullseye as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

ENV MODEL_PATH='/opt/tmp/model.pkl'

ARG DATASET_PATH='https://raw.githubusercontent.com/etelvinaoliveira/TP-Cloud/main/datasets/2023_spotify_ds1.csv'
ENV DATASET_PATH=${DATASET_PATH}

ARG MODEL_VERSION='1.0.0'
ENV MODEL_VERSION=${MODEL_VERSION}

WORKDIR /app

# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.cache/pip to speed up subsequent builds.
# Leverage a bind mount to requirements.txt to avoid having to copy them into
# into this layer.
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

# Switch to the non-privileged user to run the application.
USER root

# Copy the source code into the container.
COPY . .

# Expose the port that the application listens on.
EXPOSE 32179

# Run the application.
CMD python ML_model.py
