---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: indraribeiro
  name: project2-pv-indraribeiro
  labels:
    type: local
spec:
  resources:
    requests:      
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  volumeName: project2-pv-indraribeiro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indramatsiendra-playlist-recommender
  template:
    metadata:
      labels:
        app: indramatsiendra-playlist-recommender
    spec:
      volumes:
        - name: playlist-recommender-volume
          persistentVolumeClaim:
            claimName: project2-pv-indraribeiro
      containers:
      - name: playlist-recommender-model
        image: docker.io/indramatsiendra/playlist_recommender_model:1
        ports:
        - containerPort: 32179
        volumeMounts:
          - name: playlist-recommender-volume
            mountPath: "/opt/tmp"
      - name: playlist-recommender-api
        image: docker.io/indramatsiendra/playlist_recommender_api:1
        ports:
        - containerPort: 32186
        volumeMounts:
          - name: playlist-recommender-volume
            mountPath: "/opt/tmp"