name: Build and Deploy

on:
  push:
    paths:
      - API/**
      - datasets/dataset_path.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          version=$(echo $jsonContent | jq -r .version)
          docker build -t indramatsiendra/playlist_recommender_api:$version -t indramatsiendra/playlist_recommender_api:latest ./API

      - name: Push Docker Image
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          version=$(echo $jsonContent | jq -r .version)
          docker push indramatsiendra/playlist_recommender_api:$version
          docker push indramatsiendra/playlist_recommender_api:latest

      - name: Modify deployment.yaml and push to github
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          version=$(echo $jsonContent | jq -r .version)
          sed -i "s/\(metadata:\s*name:\s*.*\)/\1playlist-recommender-deployment:${version}/" deployment.yaml
          
          git config --global user.name 'etelvinaoliveira'
          git config --global user.email 'etelvina.oliveira2003@gmail.com'
          git remote set-url origin https://etelvinaoliveira:${{ secrets.DOCKER_TOKEN }}@github.com/etelvinaoliveira/TP-Cloud.git

          git add deployment.yaml
          git commit -m "Update deployment.yaml through github workflow" 
          git config pull.rebase false
          git pull
          git push