name: Build and Deploy

on:
  push:
    paths:
      - ML_model/**
      - datasets/dataset_path.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          datasetUrl=$(echo $jsonContent | jq -r .path)
          version=$(echo $jsonContent | jq -r .version)
          docker build --build-arg DATASET_PATH=$datasetUrl --build-arg MODEL_VERSION=$version -t indramatsiendra/playlist_recommender_model:$version -t indramatsiendra/playlist_recommender_model:latest ./ML_model

      - name: Push Docker Image
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          version=$(echo $jsonContent | jq -r .version)
          docker push indramatsiendra/playlist_recommender_model:$version
          docker push indramatsiendra/playlist_recommender_model:latest

      - name: Modify deployment.yaml
        run: |
          jsonContent=$(cat datasets/dataset_path.json)
          version=$(echo $jsonContent | jq -r .version)
          sed -i "s/\(metadata:\s*name:\s*\).*/\1playlist-recommender-api-deployment:${version}" deployment.yaml
